# Generated by Django 3.1 on 2020-08-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_readtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='model_pic',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
